"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['fitsview.py']
DATA_FILES = []

PLIST = {
    'NSHumanReadableCopyright' : '(c) Tom Badran 2013',
    'CFBundleName' : 'Fits Viewer',
    'CFBundlePackageType' : 'APPL',
    'CFBundleExecutable' : 'Fits Viewer',
    'CFBundleDisplayName' : 'Fits Viewer',
    'CFBundleShortVersionString':'0.1.0'
}

OPTIONS = {
    'argv_emulation': True, 'includes': ['sip', 'PyQt4._qt'],
    'excludes': ['PyQt4.QtDesigner', 'PyQt4.QtNetwork', 'PyQt4.QtOpenGL', 'PyQt4.QtScript', 'PyQt4.QtSql', 'PyQt4.QtTest', 'PyQt4.QtWebKit', 'PyQt4.QtXml', 'PyQt4.phonon'],
    'iconfile':'ui/icon.icns',
    'plist': PLIST
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
